### ISSUE TITLE
Window not defined when using with NextJS

### ISSUE THREAD

**Issue by NicuB93** [digitalfabrik/react-sticky-headroom#33]
When using with NextJS, I get:
`ReferenceError: window is not defined`

Steps to reproduce: 
1. Create a project with `yarn create next-app --typescript`;
2. Create a functional header component;
3. Wrap it with React Sticky Headroom component;
4. See error.

**Comment by NicuB93** [comment]
Nevermind.
I've found the solution.
The thing is, NextJS works as SSR so we need to disable SSR white importing it. We do it like so: 
`
import dynamic from "next/dynamic";

const StickyHeadroom = dynamic(
  () => import("@integreat-app/react-sticky-headroom"),
  { ssr: false }
);
`

**Comment by Schedulaar** [comment]
Thanks for opening the issue! As you already recognized, ReactStickyHeadroom is a client-side library and hence does not support SSR a priori. Thanks for also adding the solution for NextJS :)
https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

**Comment by andykimchris** [comment]
Thank you for this @NicuB93  @michael-markl . If this would be added to the documentation, that would be awesome.

**Comment by michael-markl** [comment]
Hi @andykimchris . I've added a sentence to the README.md.
